### ISSUE TITLE
fix heap corruption on Windows (MSVC2013, Debug)

### ISSUE THREAD

**Issue by mrexodia** [hteso/iaito#100]
On Windows opening a file will lead to heap corruption. It is most likely related to race conditions with the webui thread but I'm still investigating.

**Comment by ballessay** [comment]
Is this on the inital file open? You suspect the WebServerThread class?

**Comment by mrexodia** [comment]
The heap corruption is detected in `r_core_new`. The only r2 call before that should be `r_cons_new` but it's super unlikely that this is the reason.

This can only be reproduced with MSVC2013 on Debug mode because that enables heap checking.

**Comment by ballessay** [comment]
I saw you wrote something about that on telegram/IRC. Well aren't those two calls the first the QRCore constructor does?

**Comment by mrexodia** [comment]
They are indeed. I'm currently writing some custom tools to try to figure out what's going on here. My best guess is that MSVC and MinGW try to use the same heap, but this shouldn't happen at all...

**Comment by ballessay** [comment]
Is mixing msvc and mingw binaries possible?

**Comment by mrexodia** [comment]
Yes definitely. MSVC has a completely isolated environment from `msvcrt.dll` (which is deprecated and used by MinGW). You just have to be careful to not mix file and allocation functions...

**Comment by mrexodia** [comment]
The issue has been tracked down to radare2 and will be solved with https://github.com/radare/radare2/pull/7223 after this is merged I will send a pull request with a massive overhaul of the core that both fixes the build on Windows and is also thread-safe.

**Comment by mrexodia** [comment]
This is fixed in #108
