### ISSUE TITLE
Add menu -> go to address + shortcut

### ISSUE THREAD

**Issue by Maijin** [hteso/iaito#116]
Add menu -> go to address + shortcut

**Comment by hteso** [comment]
There are already many ways to jump to other locations:

- Omnibar (shortcut "G" and "S")
- Double-click in disassembly 
- Other panels double-click

Now that #117 is closed, and once documentation is available for users, there will be no need for more options. Adding to many ways of doing things is against UX and confuses the users.

**Comment by Maijin** [comment]
I'm ok with that
