### ISSUE TITLE
Sections panel not resizing properly

### ISSUE THREAD

**Issue by hteso** [hteso/iaito#129]
The sections panel doesn't behave properly with resizing. The widgets in the DockWidget don't resize to match the size of the dock until the Splitter handle us dragged :/

**Comment by mrexodia** [comment]
So this is only on startup? If that's the case it can probably be fixed by manually emitting a `resizeEvent`

**Comment by hteso** [comment]
Actually it starts with the proper size, the problems comes when resizing the section dock, that the child widgets don't resize to match the new dock size.

**Comment by hteso** [comment]
Found the fix :) I'll finish and clean the code and the push the commit.
