### ISSUE TITLE
Latest git fails to compile

### ISSUE THREAD

**Issue by DigiAngel** [hteso/iaito#130]
Git commit is e857437949c35dbe4a197dac114f6c276332385b.  This was working a week ago, now the below:
![screenshot from 2017-04-12 06-01-38](https://cloud.githubusercontent.com/assets/947191/24956650/deee34ce-1f45-11e7-84e6-e349ca4993d9.png)

Anything I can do on my end to troubleshoot?  Thank you.

**Comment by ballessay** [comment]
Have you updated the git submodule and reinstalled radare2?

**Comment by DigiAngel** [comment]
I believe so...just a git pull right?  And I don't see the radare2 git
anymore on the repo page?  https://github.com/hteso?tab=repositories.
 Thank you.

**Comment by circleous** [comment]
Radare2 fork from hteso is deleted. Thats why he makes it as submodule. Just use radare2 from latest git, or use the one from submodule as recommended in README.md

**Comment by DigiAngel** [comment]
Thanks all...I just started over and it compiled just fine...thanks again.
