### ISSUE TITLE
Graph view not working with r2 1.4

### ISSUE THREAD

**Issue by hteso** [hteso/iaito#141]
The Graph view is not working with r2 1.4 release.

**Comment by radare** [comment]
Wat

**Comment by DigiAngel** [comment]
I concur.

**Comment by hteso** [comment]
Don't panic @radare, it's an Iaitō issue :)

**Comment by DigiAngel** [comment]
LoL...good deal...thanks for the hard work!

**Comment by ballessay** [comment]
I think it's an update issue. If you reload with the context menu the graph looks okay.

**Comment by mrexodia** [comment]
I just tested, it works great on Windows with 64 bit, but shows an empty screen on 32 bit...

**Comment by radare** [comment]
With the same binary?

**Comment by hteso** [comment]
In my OS X it doesn't work, neither if I reload manually with the context menu. Any other OS X user can test and share results?

**Comment by hteso** [comment]
I tried with a 64bits binary and the graph "works", I need to manually reload after moving to another function but it shows the graph.

**Comment by pwntester** [comment]
For me it works ok on both 32bits and 64 bits binaries. But it was not updated after changing functions.
QT5.6 uses QWebEngine which is based in Chromium and by default uses a cache. First call to `index.html#<offset>` works ok, but following calls are fetched from the cache and therefore the graph is not updated.
Apparently the way to disable cache is enabled in 5.7 (https://doc.qt.io/qt-5/qwebengineprofile.html)
As a workaround, I just call the JS function to draw the graph again
