### ISSUE TITLE
use pkg-config

### ISSUE THREAD

**Issue by condret** [hteso/iaito#146]
use pkg-config in the build for finding r2 headers and libs

**Comment by radare** [comment]
Wasnt this done already?

**Comment by ballessay** [comment]
@radare Yes, the qmake !win build uses pkg-config since c57862912186c97eed5898b537816632e11a0e5e.

@condret Do you use cmake?

**Comment by ballessay** [comment]
I've modified the CMakeList.txt file to use pkg-config if not on windows, see: https://github.com/ballessay/iaito/commit/2c2a4cdfe23f9ac1f7f7709c057120a7eb3d84e5

As before, windows build needs parts of the current solution. Would be nice if a windows user could check if this still works. (And maybe someone who is more fluent in cmake if this ENV stuff is needed)

**Comment by ballessay** [comment]
Should be fixed with fd80443b7edfb6b598d0c1975ed461791bd0bb53
