### ISSUE TITLE
Crash scrolling in hexdump

### ISSUE THREAD

**Issue by wyrex** [hteso/iaito#163]
I was looking at hexdump view and tried to scroll down when iaito started spamming
```
debug output: End is coming
```
and everything became unresponsive until  I Ctrl-C killed the program.
https://gist.github.com/wyrex/7ee93ecf2f3323ac165a2af72b22104f

**Comment by ballessay** [comment]
Should be fixed with 6ffb18e6e4838b03d5c7d0f8689e011067228453

Thanks for reporting.
