### ISSUE TITLE
Linux  -  undefined references on build

### ISSUE THREAD

**Issue by dashnine** [hteso/iaito#178]
When building on Linux (Backbox, a pentesting Ubuntu variety) I'm getting undefined reference issues on a fresh install.  Output below.

I pulled using the following:
```
git clone --recurse-submodules https://github.com/hteso/iaito.git
cd iaito/
cd radare2/
sys/install.sh
```

I saw no errors on the radare2 install.

```
~/git/iaito$ git log -1
commit b7e9afc140af0d1377a8b2587aa3cf5515d18a05
Author: Hugo Teso <hugo.teso@gmail.com>
Date:   Fri May 26 10:52:17 2017 +0200
```

I then opened up qtcreator and attempted a fresh build.

[trimmed output from QtCreator]
g++ -c -pipe -g -std=gnu++0x -Wall -W -D_REENTRANT -fPIC -DAPP_VERSION=\"1.0-dev\" -DQT_QML_DEBUG -DQT_WEBENGINEWIDGETS_LIB -DQT_WIDGETS_LIB -DQT_WEBENGINE_LIB -DQT_WEBENGINECORE_LIB -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_WEBCHANNEL_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_POSITIONING_LIB -DQT_CORE_LIB -I../src -I. -I../src -I/usr/include/libr -I../../../Qt5.6.2/5.6/gcc_64/include -I../../../Qt5.6.2/5.6/gcc_64/include/QtWebEngineWidgets -I../../../Qt5.6.2/5.6/gcc_64/include/QtWidgets -I../../../Qt5.6.2/5.6/gcc_64/include/QtWebEngine -I../../../Qt5.6.2/5.6/gcc_64/include/QtWebEngineCore -I../../../Qt5.6.2/5.6/gcc_64/include/QtQuick -I../../../Qt5.6.2/5.6/gcc_64/include/QtGui -I../../../Qt5.6.2/5.6/gcc_64/include/QtWebChannel -I../../../Qt5.6.2/5.6/gcc_64/include/QtQml -I../../../Qt5.6.2/5.6/gcc_64/include/QtNetwork -I../../../Qt5.6.2/5.6/gcc_64/include/QtPositioning -I../../../Qt5.6.2/5.6/gcc_64/include/QtCore -I. -I. -I../../../Qt5.6.2/5.6/gcc_64/mkspecs/linux-g++ -o moc_consolewidget.o moc_consolewidget.cpp
g++ -Wl,-rpath,/home/flux/Qt5.6.2/5.6/gcc_64/lib -Wl,-rpath-link,/home/flux/Qt5.6.2/5.6/gcc_64/lib -o iaito main.o mainwindow.o newfiledialog.o optionsdialog.o highlighter.o qrcore.o createnewdialog.o hexascii_highlighter.o pieview.o sectionswidget.o codegraphic.o notepad.o mdhighlighter.o functionswidget.o renamedialog.o aboutdialog.o importswidget.o symbolswidget.o relocswidget.o commentswidget.o stringswidget.o flagswidget.o memorywidget.o exportswidget.o qrdisasm.o sdbdock.o analthread.o commentsdialog.o sidebar.o helpers.o omnibar.o dashboard.o xrefsdialog.o hexhighlighter.o sectionsdock.o consolewidget.o radarewebserver.o qrc_resources.o moc_mainwindow.o moc_newfiledialog.o moc_optionsdialog.o moc_highlighter.o moc_qrcore.o moc_createnewdialog.o moc_hexascii_highlighter.o moc_pieview.o moc_sectionswidget.o moc_codegraphic.o moc_notepad.o moc_mdhighlighter.o moc_functionswidget.o moc_renamedialog.o moc_aboutdialog.o moc_importswidget.o moc_symbolswidget.o moc_relocswidget.o moc_commentswidget.o moc_stringswidget.o moc_flagswidget.o moc_memorywidget.o moc_exportswidget.o moc_sdbdock.o moc_analthread.o moc_commentsdialog.o moc_sidebar.o moc_omnibar.o moc_dashboard.o moc_xrefsdialog.o moc_hexhighlighter.o moc_sectionsdock.o moc_consolewidget.o   -lr_core -lr_config -lr_cons -lr_cmd -lr_util -lr_flags -lr_asm -lr_lib -lr_db -lr_debug -lr_hash -lr_bin -lr_lang -lr_io -lr_anal -lr_parse -lr_bp -lr_egg -lr_reg -lr_search -lr_syscall -lr_sign -lr_diff -lr_socket -lr_fs -lmagic -L/home/flux/Qt5.6.2/5.6/gcc_64/lib -lQt5WebEngineWidgets -L/usr/lib64 -lQt5Widgets -lQt5WebEngine -lQt5WebEngineCore -lQt5Quick -lQt5Gui -lQt5WebChannel -lQt5Qml -lQt5Network -lQt5Positioning -lQt5Core -lGL -lpthread 
qrcore.o: In function `QRCore::getFunctionRefs(unsigned long long, char)':
/home/flux/git/iaito/build-iaito-Desktop_Qt_5_6_2_GCC_64bit-Debug/../src/qrcore.cpp:91: undefined reference to `r_anal_get_fcn_in'
qrcore.o: In function `QRCore::getCycloComplex(unsigned long long)':
/home/flux/git/iaito/build-iaito-Desktop_Qt_5_6_2_GCC_64bit-Debug/../src/qrcore.cpp:115: undefined reference to `r_anal_get_fcn_in'
qrcore.o: In function `QRCore::getFcnSize(unsigned long long)':
/home/flux/git/iaito/build-iaito-Desktop_Qt_5_6_2_GCC_64bit-Debug/../src/qrcore.cpp:133: undefined reference to `r_anal_get_fcn_in'
qrcore.o: In function `QRCore::sdbList(QString)':
/home/flux/git/iaito/build-iaito-Desktop_Qt_5_6_2_GCC_64bit-Debug/../src/qrcore.cpp:151: undefined reference to `sdb_ns_path'
qrcore.o: In function `QRCore::sdbListKeys(QString)':
/home/flux/git/iaito/build-iaito-Desktop_Qt_5_6_2_GCC_64bit-Debug/../src/qrcore.cpp:169: undefined reference to `sdb_ns_path'
/home/flux/git/iaito/build-iaito-Desktop_Qt_5_6_2_GCC_64bit-Debug/../src/qrcore.cpp:174: undefined reference to `sdb_foreach_list'
qrcore.o: In function `QRCore::sdbGet(QString, QString)':
/home/flux/git/iaito/build-iaito-Desktop_Qt_5_6_2_GCC_64bit-Debug/../src/qrcore.cpp:187: undefined reference to `sdb_ns_path'
/home/flux/git/iaito/build-iaito-Desktop_Qt_5_6_2_GCC_64bit-Debug/../src/qrcore.cpp:190: undefined reference to `sdb_const_get'
qrcore.o: In function `QRCore::sdbSet(QString, QString, QString)':
/home/flux/git/iaito/build-iaito-Desktop_Qt_5_6_2_GCC_64bit-Debug/../src/qrcore.cpp:200: undefined reference to `sdb_ns_path'
qrcore.o: In function `QRCore::cmd(QString const&)':
/home/flux/git/iaito/build-iaito-Desktop_Qt_5_6_2_GCC_64bit-Debug/../src/qrcore.cpp:220: undefined reference to `r_mem_free'
qrcore.o: In function `QRCore::cmdj(QString const&)':
/home/flux/git/iaito/build-iaito-Desktop_Qt_5_6_2_GCC_64bit-Debug/../src/qrcore.cpp:242: undefined reference to `r_mem_free'
qrcore.o: In function `QRCore::tryFile(QString, bool)':
/home/flux/git/iaito/build-iaito-Desktop_Qt_5_6_2_GCC_64bit-Debug/../src/qrcore.cpp:436: undefined reference to `sdb_bool_set'
qrcore.o: In function `QRCore::getList(QString const&, QString const&)':
/home/flux/git/iaito/build-iaito-Desktop_Qt_5_6_2_GCC_64bit-Debug/../src/qrcore.cpp:452: undefined reference to `sdb_const_get'
qrcore.o: In function `QRCore::fcnBasicBlockCount(unsigned long long)':
/home/flux/git/iaito/build-iaito-Desktop_Qt_5_6_2_GCC_64bit-Debug/../src/qrcore.cpp:497: undefined reference to `r_anal_get_fcn_in'
qrcore.o: In function `QRCore::fcnEndBbs(QString)':
/home/flux/git/iaito/build-iaito-Desktop_Qt_5_6_2_GCC_64bit-Debug/../src/qrcore.cpp:510: undefined reference to `r_anal_get_fcn_in'
qrcore.o: In function `QRCore::functionAt(unsigned long long)':
/home/flux/git/iaito/build-iaito-Desktop_Qt_5_6_2_GCC_64bit-Debug/../src/qrcore.cpp:611: undefined reference to `r_anal_get_fcn_in'
collect2: error: ld returned 1 exit status
make: *** [iaito] Error 1
09:44:05: The process "/usr/bin/make" exited with code 2.
Error while building/deploying project iaito (kit: Desktop Qt 5.6.2 GCC 64bit)
When executing step "Make"
09:44:05: Elapsed time: 01:35.

Anything obvious I'm missing?

**Comment by ballessay** [comment]
Looks like an old r2 version. Have you installed radare2 (or is it in that distribution by default)? Can you check `r2 -version` and `which r2`?

**Comment by dashnine** [comment]
Definitely attempted to install r2 using the version provided a la --recurse-submodules, but perhaps it didn't install cleanly?

~/git/iaito/radare2$ r2 -version
radare2 1.5.0-git 14869 @ linux-x86-64 git.1.4.0-186-g02a905c
commit: 02a905c5a4a564d398d4a0fcee7b5fc85d7ecf8c build: 2017-05-26__09:30:38
~/git/iaito/radare2$ which r2
/usr/bin/r2

**Comment by ballessay** [comment]
Strange the `r2 -version` output looks ok to me. Can you check if there is really no distribution package installed (e. g. `dpkg -l radare2` (or what the package is called there)) and which libs that r2 is using `ldd $(which r2)`?

**Comment by dashnine** [comment]
Doesn't seem to be one:

(thanks again for your help!)

`flux@serene-dev:~/git/iaito/radare2$ dpkg -l radare2
dpkg-query: no packages found matching radare2
flux@serene-dev:~/git/iaito/radare2$ sudo apt-get remove radare2
[sudo] password for flux: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package 'radare2' is not installed, so not removed
The following packages were automatically installed and are no longer required:
  libbotan-1.10-0 libgconf2-4 libmagic-dev libqt5clucene5 libqt5declarative5
  libqt5designer5 libqt5designercomponents5 libqt5help5 libqt5positioning5
  libqt5qml5 libqt5quick5 libqt5quickparticles5 libqt5quicktest5 libqt5script5
  libqt5sensors5 libqt5svg5 libqt5webkit5 libradare2-0.9.6 libradare2-common
  libradare2-dev qmlscene qtcreator-doc qtdeclarative5-controls-plugin
  qtdeclarative5-dev qtdeclarative5-quicklayouts-plugin
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
flux@serene-dev:~/git/iaito/radare2$ ldd $(which r2)
	linux-vdso.so.1 =>  (0x00007ffe67bf6000)
	libr_core.so => /usr/lib/libr_core.so (0x00007f90d6f55000)
	libr_parse.so => /usr/lib/libr_parse.so (0x00007f90d6cff000)
	libr_search.so => /usr/lib/libr_search.so (0x00007f90d6af8000)
	libr_cons.so => /usr/lib/libr_cons.so (0x00007f90d68da000)
	libr_config.so => /usr/lib/libr_config.so (0x00007f90d66d4000)
	libr_bin.so => /usr/lib/libr_bin.so (0x00007f90d639e000)
	libr_debug.so => /usr/lib/libr_debug.so (0x00007f90d6172000)
	libr_anal.so => /usr/lib/libr_anal.so (0x00007f90d5779000)
	libr_reg.so => /usr/lib/libr_reg.so (0x00007f90d556e000)
	libr_bp.so => /usr/lib/libr_bp.so (0x00007f90d5368000)
	libr_io.so => /usr/lib/libr_io.so (0x00007f90d50fe000)
	libr_fs.so => /usr/lib/libr_fs.so (0x00007f90d4ebe000)
	libr_asm.so => /usr/lib/libr_asm.so (0x00007f90d4331000)
	libr_syscall.so => /usr/lib/libr_syscall.so (0x00007f90d412b000)
	libr_hash.so => /usr/lib/libr_hash.so (0x00007f90d3f1e000)
	libr_magic.so => /usr/lib/libr_magic.so (0x00007f90d3d0a000)
	libr_flag.so => /usr/lib/libr_flag.so (0x00007f90d3b03000)
	libr_egg.so => /usr/lib/libr_egg.so (0x00007f90d38f0000)
	libr_crypto.so => /usr/lib/libr_crypto.so (0x00007f90d36c7000)
	libr_util.so => /usr/lib/libr_util.so (0x00007f90d33ec000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f90d3023000)
	libr_lang.so => /usr/lib/libr_lang.so (0x00007f90d2e1c000)
	libr_socket.so => /usr/lib/libr_socket.so (0x00007f90d2c0f000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f90d2908000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f90d26ea000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f90d24e5000)
	/lib64/ld-linux-x86-64.so.2 (0x000056550c7b2000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f90d22e2000)
`

I suppose I could spin up a fresh, non-backbox garden-variety ubuntu and try that as a last resort.  Just wish I knew *why*!

**Comment by dashnine** [comment]
Hurk.  Ran autoremove, deleted and redownloaded the iaito project, reran and reinstalled radare, and I'm clean now.  I'd swear I've done all this before--but there you have it. >_>  Thanks!

**Comment by ballessay** [comment]
Well my guess wasn't that bad, see the packages were marked for autoremove but still there: `libradare2-0.9.6 libradare2-common` ;)
