### ISSUE TITLE
Build failure on Linux x64

### ISSUE THREAD

**Issue by thejeswi** [hteso/iaito#198]
On using "cmake src", I get the error:

> Add the installation prefix of "Qt5WebEngine" to CMAKE_PREFIX_PATH or set
>   "Qt5WebEngine_DIR" to a directory containing one of the above files.  If
>   "Qt5WebEngine" provides a separate development package or SDK, be sure it
>   has been installed.

I have Qt5WebEngine installed.

**Comment by radare** [comment]
Try with r2pm. It properly sets the environment to make cmake watch qt, you have to set some environment iirc

Just r2pm -i iaito

**Comment by thestr4ng3r** [comment]
The error basically says what you have to do. Set `CMAKE_PREFIX_PATH` to the prefix (make sure it is really the prefix containing bin, lib, ...) of your Qt installation that includes Qt5WebEngine:
```
cmake -DCMAKE_PREFIX_PATH=/path/to/Qt ..
```
or use r2pm as suggested

**Comment by xarkes** [comment]
Do you still have this issue ?
