### ISSUE TITLE
remove sleep and fork

### ISSUE THREAD

**Issue by mrexodia** [hteso/iaito#20]
- [x] sleep
- [x] fork

They are not cross platform and should be replaced with Qt APIs.

**Comment by trufae** [comment]
There are r2 apis that do that in a portable way. But using qt would be better for the gui

**Comment by mrexodia** [comment]
Okay this issue can be closed after pull request #24 is merged.

**Comment by hteso** [comment]
Fixed with #24

**Comment by trufae** [comment]
👍👍👍 for removing sleep. Its an useless activity
