### ISSUE TITLE
vs build error：error C2001: newline in constant

### ISSUE THREAD

**Issue by stonedreamforest** [hteso/iaito#200]
`1>C:\Users\Administrator\Documents\GitHub\iaito\iaito_win32\radare2\include\libr\r_cons.h(273): error C2001: newline in constant`

“r_cons.h” need Save as “utf-8” format

**Comment by radare** [comment]
Wat

**Comment by stonedreamforest** [comment]
![2017-07-30_20-56-45](https://user-images.githubusercontent.com/16742566/28753641-3d2ebbd8-756a-11e7-9400-e80f1c2d9d4f.gif)

**Comment by radare** [comment]
I dont see any constant or newline in this line. I dont have windows either, so if you have a fix pls send a pr and ill review

**Comment by stonedreamforest** [comment]
yeah，I don't see any constant or newline in this line too,the tips  from visual studio

**Comment by stonedreamforest** [comment]
If only the file format is changed, do not change the contents of the file，can't send a pr
