### ISSUE TITLE
iaito version 

### ISSUE THREAD

**Issue by adrain09** [hteso/iaito#204]
when i updated the radare2,the iaito push:

The version used to compile iaito (1.6.0-344-ge900b49) does not match the binary version of radare2 (1.6.0-399-ga635b34). This could result in unexpected behaviour. Are you sure you want to continue?

**Comment by Maijin** [comment]
https://github.com/hteso/iaito#requirements

**Comment by xarkes** [comment]
As stated by Maijin your version of radare2 is wrong. Use the one in this repository as stated by the README.
