### ISSUE TITLE
Error when building with cmake

### ISSUE THREAD

**Issue by Razer0901** [hteso/iaito#211]
Hello, 

I'm having trouble building iaito for OS X 10.12.6. The error is as follows:
```
Generating qrc source iaito_automoc.dir/qrc_resources_HAS2BXGMQQBHVI.cpp
[  2%] Built target iaito_automoc
Scanning dependencies of target iaito
[  4%] Building CXX object CMakeFiles/iaito.dir/main.cpp.o
[  6%] Building CXX object CMakeFiles/iaito.dir/mainwindow.cpp.o
[  9%] Building CXX object CMakeFiles/iaito.dir/newfiledialog.cpp.o
[ 11%] Building CXX object CMakeFiles/iaito.dir/optionsdialog.cpp.o
[ 13%] Building CXX object CMakeFiles/iaito.dir/highlighter.cpp.o
[ 16%] Building CXX object CMakeFiles/iaito.dir/qrcore.cpp.o
/Users/******/Documents/iaito/src/qrcore.cpp:388:28: error: no member named 'desc' in
      'r_core_file_t'
    bool is_writable = cf->desc->flags & R_IO_WRITE;
                       ~~  ^
1 error generated.
make[2]: *** [CMakeFiles/iaito.dir/qrcore.cpp.o] Error 1
make[1]: *** [CMakeFiles/iaito.dir/all] Error 2
make: *** [all] Error 2
```

I installed qt with brew `brew install qt` which installed it in /usr/local/Cellar/qt/5.9.1.
After running `cmake -DCMAKE_PREFIX_PATH=/usr/local/Cellar/qt/5.9.1 ..` everything seemed fine until I ran `make` (which resulted in the error above).

Any help would be greatly appreciated!

-xRaZx

**Comment by Maijin** [comment]
The README explicitely say which version of Qt to use.

**Comment by radare** [comment]
iaito uses an old version of r2,nobody updated it for a bunch of months

**Comment by xarkes** [comment]
Now that r2 is green again, we can update it.

**Comment by radare** [comment]
yes please

**Comment by xarkes** [comment]
I updated the radare2 version, so you should not have this error anymore. Also I think iaito is compatible with Qt 5.9.1.
