### ISSUE TITLE
Hangs and crashes on macOS

### ISSUE THREAD

**Issue by ylluminarious** [hteso/iaito#212]
I built `iaito` on macOS 10.12.6 with the following commands:

```zsh
$ cmake -DCMAKE_PREFIX_PATH=/usr/local/Cellar/qt/5.9.1 ..
$ # the following four commands are to fix errors about openssl from radare2
$ LD_LIBRARY_PATH=/usr/local/opt/openssl/lib:"${LD_LIBRARY_PATH}"
$ CPATH=/usr/local/opt/openssl/include:"${CPATH}"
$ PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig:"${PKG_CONFIG_PATH}"
$ export LD_LIBRARY_PATH CPATH PKG_CONFIG_PATH
$ make
```

I tried to run `iaito` on a random app's binary (just to test it out) and it sat there for a bit, saying that it's analyzing. Then it crashed with a bus error:

```
syntax error: error in error handling
syntax error: error in error handling
syntax error: error in error handling
FILE OPEN (/Applications/MyApp.app/Contents/MacOS/MyApp)
arw 00000000000000000000000000000000000000000000000000000000000000000000000000000000f82300000000000000000000000000000000000000000000
BITS 32
[js: Uncaught ReferenceError: MEOW is not definedy0 (aa)
js: Uncaught ReferenceError: MEOW is not defined
js: Uncaught ReferenceError: MEOW is not defined
[1]    8664 bus error  ./iaito
```

As a sanity check, I then tried to run `iaito` on a "hello world" binary, which has the following source code (to show there's nothing fancy going on here):

```c
#include <stdio.h>
main() {
	 printf("hello, world\n");
}
```

And when I did that, `iaito` just hung. I finally did `^C`, which yielded a message about a segfault:

```
syntax error: error in error handling
syntax error: error in error handling
syntax error: error in error handling
FILE OPEN (/Users/my_username/a.out)
BITS 64
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze len bytes of instructions for references (aar)
[x] Analyze function calls (aac)
[ ] [*] Use -AA or aaaa to perform additional experimental analysis.
[x] Constructing a function name for fcn.* and sym.func.* functions (aan))
No project
Starting http server...
open http://localhost:9090/
r2 -C http://localhost:9090/cmd/
^C[1]    9022 segmentation fault  ./iaito
```

It's probably worth noting that, according to homebrew, I'm using Qt 5.9.1 and I also have radare2 installed via homebrew, which is on v1.6.0.

**Comment by xarkes** [comment]
Hello,
This is probably because your radare2 version is not the same as the one which is in the repository. The currently supported radare2 version is commit `55362b409b98a97b0f9ccf1b50b61510bfa80816`. Any other version might not behave as expected.

**Comment by ylluminarious** [comment]
@xarkes Thanks! Using the version from the repository fixed the problem. Though, it would probably be good if people could use newer versions...

**Comment by xarkes** [comment]
Yes I will update the radare2 version, last months radare2 was not stable so I could not update it.

**Comment by ylluminarious** [comment]
Ah, I see.

**Comment by ylluminarious** [comment]
@xarkes By the way, this is off-topic, but is it possible for me to use AT&T syntax in `iaito`? I have the following line in my `.radare2rc`:
```
e asm.syntax=att
```
And it works fine in plain `r2`. But it has no effect in `iaito`, it seems.

**Comment by xarkes** [comment]
Yes, .radare2rc is not very well handled for now in iaito. There's an option in the View dropdown menu which allows you to choose the asm syntax.

**Comment by ylluminarious** [comment]
@xarkes Awesome, thanks again.
