### ISSUE TITLE
"?d call" doesn't work

### ISSUE THREAD

**Issue by mrexodia** [hteso/iaito#22]
It prints an empty result.

**Comment by trufae** [comment]
Works perfectly from r2pipe i guess thats because iaito is not able to find the sdb files for that arch.

**Comment by hteso** [comment]
Works in OS X and Linux, could be an issue specific of the Windows build?

**Comment by mrexodia** [comment]
I think the reason is that the r2 api doesn't have some environment
variables or something set correctly.

**Comment by mrexodia** [comment]
Okay the reason was that r2 uses the current directory to look for the `share` etc folders. I was starting from Qt Creator, which calls `build-blahblah\debug\Iaito.exe` but has the starting directory `build-blahblah\` copying r2 to this directory solved the problem.

**Comment by trufae** [comment]
Any proposal to solve that in r2land? Maybe adding an api (or just add an eval var) to change the prefix in runtime?

**Comment by mrexodia** [comment]
basically the solution is to check from iaito if the folders are in the right location and just warn the user on startup...

**Comment by trufae** [comment]
Why warn the user? Iaito knows where r2 is, and you can just chdir to that dire before corenew() and wverything should work

**Comment by mrexodia** [comment]
It might know where r2 is but it doesn't know if the share directory is
there.

**Comment by trufae** [comment]
The share directory is in r2 one because its relative

**Comment by trufae** [comment]
(On windows builds should be like this, if not thats a regression in our windows builds)

**Comment by hteso** [comment]
Fixed with #24
