### ISSUE TITLE
Unable to install www-p

### ISSUE THREAD

**Issue by nxion** [hteso/iaito#25]
Hi,

Having issues setting up the UI. I installed using the user script so it all contained inside my home directory. When trying to install `www-p` I receive the below error:

```
Processing www-p ...
error: cannot open .git/FETCH_HEAD: Permission denied

Install Done For www-p
make -C www/p build
make[1]: Entering directory '/home/me/.config/radare2/r2pm/git/radare2-webui/www/p'
npm install
make[1]: npm: Command not found
Makefile:5: recipe for target 'node_modules' failed
make[1]: *** [node_modules] Error 127
make[1]: Leaving directory '/home/me/.config/radare2/r2pm/git/radare2-webui/www/p'
Makefile:28: recipe for target 'panel' failed
make: *** [panel] Error 2
```

My guess is that I need to install NPM separately? I also tried another package just to see if it was the `www-p` that was having issues. When running `r2pm -i python` it just says `Cannot find`.

My machine is Ubuntu 16.04.2 LTS x64.

Thanks

**Comment by nxion** [comment]
I really was not paying attention. My apologies. There is no issue...

**Comment by trufae** [comment]
First of all theres a permission denied error so i guess you tried to run that as root first with sudo instead of -g

I would clean that up and retry if not working. But this issue should go in the radare2-webui repo as long as its completely unrelated to iaito

**Comment by nxion** [comment]
I appreciate your response but I figured it out. I needed to install Node and npm. After I did that, it installed and compiled  fine. It was my mistake I wasn't paying full attention to what I was doing :/
