### ISSUE TITLE
iaito should pick a new port if 9090 (or whatever is configured) is in use

### ISSUE THREAD

**Issue by crowell** [hteso/iaito#26]
if I have 2 copies of iaito open, only one of them can do graphs, because only one can bind to 9090

**Comment by trufae** [comment]
This should be fixed in r2. Maybe just having http.port to be a range instead of a number and try port by port incrementing by 1 until it works. Iaito should check that var to load the right site

**Comment by hteso** [comment]
@trufae is that now solved from r2land?

**Comment by trufae** [comment]
yes, i also fixed iaito to grab the correct port

**Comment by hteso** [comment]
Closed then?

**Comment by Jo-Con-El** [comment]
Please reopen if it's not fixed already.
