### ISSUE TITLE
Graph View Doesn't work

### ISSUE THREAD

**Issue by agnosticlines** [hteso/iaito#29]
When disassembling /bin/ls and pressing space on Arch Linux running the listed radare2 version the graph won't load. www-p has been installed.

> Module version mismatch /home/test/.config/radare2/plugins/bin_mdmp.so (1.1.0-git) vs (1.4.0-git)
> QRCore::tryFile: Cannot open file?
> libpng warning: iCCP: known incorrect sRGB profile
> QMetaObject::connectSlotsByName: No matching signal for on_backButton_clicked()
> libpng warning: iCCP: known incorrect sRGB profile
> BITS 64
> [x] Analyze all flags starting with sym. and entry0 (aa)
> [x] Analyze len bytes of instructions for references (aar)
> [x] Analyze function calls (aac)
> [ ] [*] Use -AA or aaaa to perform additional experimental analysis.
> [x] Constructing a function name for fcn.* and sym.func.* functions (aan))
> Cannot open project info (/home/test/.config/radare2/projects/ls/rc)
> Cannot retrieve information for project '/home/test/.config/radare2/projects/ls/rc'
> No project
> Starting http server...
> open http://localhost:14170/
> r2 -C http://localhost:14170/cmd/
> FAILED TO LAUNCH

**Comment by Xiaogrill** [comment]
I have the same issues, running the submodule radare2.
The Graph view is just blank.

```
λ uname -a
Linux machine 4.10.7_1 #1 SMP PREEMPT Thu Mar 30 20:57:30 UTC 2017 x86_64 GNU/Linux
```
```
λ r2 -v
radare2 1.4.0-git 14327 @ linux-x86-64 git.1.3.0-228-g4715f1e2b
commit: 4715f1e2b9394aac832ff5f37e6a7504c59fd993 build: 2017-03-31__22:43:53
```
```
λ ./iaito
QRCore::tryFile: Cannot open file?
libpng warning: iCCP: known incorrect sRGB profile
QMetaObject::connectSlotsByName: No matching signal for on_backButton_clicked()
libpng warning: iCCP: known incorrect sRGB profile
FILE OPEN (/bin/ls)
BITS 64
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze len bytes of instructions for references (aar)
[x] Analyze function calls (aac)
[ ] [*] Use -AA or aaaa to perform additional experimental analysis.
[x] Constructing a function name for fcn.* and sym.func.* functions (aan))
Cannot open project info (/home/user/.config/radare2/projects/ls/rc)
Cannot retrieve information for project '/home/user/.config/radare2/projects/ls/rc'
No project
Starting http server...
open http://localhost:14170/
r2 -C http://localhost:14170/cmd/
FAILED TO LAUNCH
```

**Comment by Maijin** [comment]
Regression it worked few days ago.

**Comment by hteso** [comment]
Should I close?

**Comment by radare** [comment]
yes
