### ISSUE TITLE
Can only display entry0 graph if space is pressed in disassembly

### ISSUE THREAD

**Issue by Maijin** [hteso/iaito#3]
I can only display entry0 main graph, via disassembly -> graph (space). The only way to switch to another graph currently is to use the top bar.

**Comment by hteso** [comment]
Correct, double-click navigation in the graph view stopped working.

**Comment by Maijin** [comment]
This works on /p so this is iailto specific

**Comment by trufae** [comment]
This issue should be reproducible in /p so maybe we should move this issue there

**Comment by Maijin** [comment]
This works on /p so this is iailto specific

**Comment by hteso** [comment]
Iaito specific issue, not graph or radare2.

**Comment by trufae** [comment]
Why programs insist so much in having code outside the entrypoint? :((

**Comment by Maijin** [comment]
This is not fixed :/

**Comment by hteso** [comment]
Nice try, but still fails if user moves by single-click to a new function. Reopening...

**Comment by hteso** [comment]
Mind trying again now @Maijin, please?

**Comment by Maijin** [comment]
OK much better. Now there is still a glitch issue when using space to come back to the the disassembly view as the offset is changed.

![image](https://cloud.githubusercontent.com/assets/1408600/24960595/876323da-1f96-11e7-96a3-790a3e94d6b2.png)

![image](https://cloud.githubusercontent.com/assets/1408600/24960601/8b3d68ee-1f96-11e7-9c6e-f6d4fd1ec469.png)

![image](https://cloud.githubusercontent.com/assets/1408600/24960605/8eeb82b4-1f96-11e7-8efa-a949943491fb.png)

**Comment by Maijin** [comment]
And since you cannot scroll up after this, this is very frustrating :/

**Comment by hteso** [comment]
The actual design of the Disassembly view has some limitations, and that behavior is one of them. I'm closing this issue and I'll create another one to address the overall disassembly view approach.
