### ISSUE TITLE
misleading exit message box

### ISSUE THREAD

**Issue by mrexodia** [hteso/iaito#36]
![misleading](https://i.imgur.com/EFbrg7u.png)

This box could be interpreted as 'do you want to save your project' but clicking 'OK' doesn't do that. I think it should be changed to a `yes/no/cancel` message box for 'do you want to save before closing?'

**Comment by CoderINusE** [comment]
Is it working on Windows?

**Comment by mrexodia** [comment]
What do you mean?

**Comment by CoderINusE** [comment]
I'd read "Windows will be added soon" in README and thought that Windows isn't supported.

**Comment by mrexodia** [comment]
It is now, I added windows support. See the pull requests.

**Comment by CoderINusE** [comment]
Yeah I see, thanks!

**Comment by trufae** [comment]
Indeed. This is confusing

**Comment by hteso** [comment]
Should we add 2 dialogs? One asking to save yes/no and another for "do you want to exit" yes/no.

**Comment by mrexodia** [comment]
Only one with yes/no/cancel

Yes - saves and exits
No - doesn't save and exits
Cancel - act like the user didn't exit and continue running
