### ISSUE TITLE
Enable filter/relsub etc in graphview

### ISSUE THREAD

**Issue by Maijin** [hteso/iaito#4]
As you can see for example entry0 is clearly lacking the basic information regarding the offset:

![image](https://cloud.githubusercontent.com/assets/1408600/24454642/e989de42-148c-11e7-93d1-8adcb553fd4c.png)

![image](https://cloud.githubusercontent.com/assets/1408600/24454625/d722252a-148c-11e7-8c8c-8bd15be0de8f.png)

**Comment by pwntester** [comment]
This is a radare issue. `agj` should return resolved offsets

**Comment by Maijin** [comment]
@radare
