### ISSUE TITLE
Change AnalThread to AnalysisThread?

### ISSUE THREAD

**Issue by chrisps** [hteso/iaito#47]
Self explanatory

**Comment by mrexodia** [comment]
I don't believe that will be needed lol

**Comment by skgsergio** [comment]
😂😂😂

You will need to go upstream with this issue https://github.com/radare/radare2/tree/master/libr/anal

**Comment by chrisps** [comment]
My god, how deep into the bowels of depravity has the RE community sunk?

**Comment by XVilka** [comment]
Deep enough to contain a pair of arms: `libr/anal/p/anal_arm_cs.c` and `libr/anal/p/anal_arm_gnu.c`

**Comment by Maijin** [comment]
@chrisps you got dirty mind, it means analysis.

**Comment by hteso** [comment]
Anal FTW!!

No, really guys, all comments considered, mind if I close the issue?

**Comment by Maijin** [comment]
please close.

**Comment by chrisps** [comment]
RIP

**Comment by mrexodia** [comment]
RIP
