### ISSUE TITLE
Install for Ubuntu Xenial Desktop 64 Bit

### ISSUE THREAD

**Issue by DigiAngel** [hteso/iaito#48]
Topic :)
~~~
sudo apt-get install libgl1-mesa-dev

git clone --recurse-submodules https://github.com/hteso/radare2-iaito.git
cd radare2-iaito
sudo sys/install.sh

git clone --recurse-submodules https://github.com/hteso/iaito.git
~~~
download and install https://download.qt.io/archive/qt/5.3/5.3.2/qt-opensource-linux-x64-5.3.2.run

start Qt-Creator, Open Project, point to iaito/src/Iaito.pro
click Configure Project, click Build -> Run
exe wil be in iaito/build-Iaito-Desktop_Qt_5_3_GCC_64bit-Debug

**Comment by ballessay** [comment]
Isn't this more like "How to setup build environment on Ubuntu"?

Sorry I don't have an Ubuntu installation at hand. But wouldn't one need build-essential git a. s. o. too?

BTW: I guess Ubuntu has qtcreator in the distribution repository

**Comment by DigiAngel** [comment]
Maybe...however, from the front page there's almost zero information on how to actually build this.  And yes...for a complete build environment you would need git and build-essentials.  I didn't see a Qt creator anywhere in the repo, but I totally could have missed it.  Long story short I was hoping to help out folks who maybe have never built anything with Qt at all, which was me :)  That and save the hunt and peck searching time when compile failed with missing GL.h.

**Comment by DigiAngel** [comment]
And as a complete aside, Hugo, this app is amazing...and is one of the few that I will pay money for.  So get a petreon or whatever donation thing you get and I will send you money.

**Comment by ballessay** [comment]
Sorry I didn't intend to sound harsh or anything. You're right, there's little information on that subject atm. Maybe a BUILD.md would help.

Just FYI (its in universe): http://packages.ubuntu.com/xenial/qtcreator

**Comment by DigiAngel** [comment]
Yep...you're totally right...I wasn't finding it cause I'd cleared the apt cache...LoL...GO ME!  I did want to make sure I had the exact version..but ya, easier to just install the thing via apt.  And you're fine...you didn't sound harsh :)  Yea...a build doc would help....would help out poor sods like me who see this awesome app and then think "well how the bugger do I get it".

**Comment by probonopd** [comment]
Check out whether this example [AppImage](http://appimage.org/) works for you:
https://transfer.sh/Ghp3k/Iaito-git.7d312b5-x86_64.AppImage

**Comment by DigiAngel** [comment]
Ah very cool thanks!

**Comment by hteso** [comment]
Hi @DigiAngel! Wiki creation and editing should be open to everyone. Mind creating a wiki page with this content for other Ubuntu users? :)

**Comment by DigiAngel** [comment]
Absolutely..thanks Hugo!

**Comment by hteso** [comment]
Thank you :) I close the issue
