### ISSUE TITLE
Graph boxes moving issue

### ISSUE THREAD

**Issue by DigiAngel** [hteso/iaito#51]
Moving graph boxes past a certain point removes the grab bar at the top makes it immovable.
![peek 2017-04-01 12-11](https://cloud.githubusercontent.com/assets/947191/24581226/b0057984-16d4-11e7-9320-8c0440675950.gif)

**Comment by hteso** [comment]
Another known bug that had no issue yet. Again, thanks for creating the issue, and with an animation! Assigned to the graph developer.

**Comment by DigiAngel** [comment]
Good deal..thank you!

**Comment by pwntester** [comment]
should be fixed in https://github.com/hteso/iaito/pull/70/commits/bbb576197cd4b893da98891fec54ab94cecb7ada

At least, the canvas has been expanded to the initial graph size + 5000px

**Comment by DigiAngel** [comment]
thanks...I'll give this a test today :)
