### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by Maijin** [hteso/iaito#65]
Should include the basic of codingstyles cc @trufae @hteso 
-> https://github.com/blog/1184-contributing-guidelines
-> https://github.com/radare/radare2/blob/master/CONTRIBUTING.md

**Comment by ballessay** [comment]
Yes that would be nice. Currently not easy to know whats right.  Maybe provide a qtcreator 'code style' template (github doesn't like xml so I renamed it to txt)? [iaito.txt](https://github.com/hteso/iaito/files/890709/iaito.txt)


About the radare2 CONTRIBUTING.md. It states: 

> Always put a space before every parenthesis (function calls, conditionals, fors, etc, ...) 

But the first switch example doesn't. ;)

BTW. currently most of the iaito code seems to be intended with spaces not tabs.

**Comment by radare** [comment]
R2 coding style doesnt needs to be the same for iaito. Different languages and different cultures. Its ok to not prefiz all parenthesis by a space
