### ISSUE TITLE
Build fails: `r_mem_free(*void)` not defined in scope

### ISSUE THREAD

**Issue by aiosin** [hteso/iaito#67]
Strange behaviour I'm noticing with my builds:

I have installed the radare2 submodule and I can find the header where `r_mem_free` is defined at the correct location on my system.

QtCreator 3.1.2 fails to build at `qrcore.cpp` at this function:
```
QString QRCore::cmd(const QString &str) {
    QByteArray cmd = str.toUtf8();
    //r_cons_flush();
    char *res = r_core_cmd_str (this->core, cmd.constData());
    QString o = QString(res ? res : "");
    //r_mem_free was added in https://github.com/radare/radare2/commit/cd28744049492dc8ac25a1f2b3ba0e42f0e9ce93
    r_mem_free(res);
    return o;
}
```
It complains that r_mem_free was not defined in scope, adding a `#include "r_util/r_mem.h` did change nothing.

This version of QtCreator uses a kit using Qt 5.3 and the system default GCC.

The other installation of QtCreator that builds and runs just fine, uses a kit with Qt 5.5.1 with the same default GCC installation.

**Comment by ballessay** [comment]
What project file are you working with? qmake or cmake? How have you installed radare2 sys/install.sh or sys/user.sh?

**Comment by aiosin** [comment]
@ballessay installed with sys/install.sh

Both of my installations of QtCreator use qmake.

**Comment by ballessay** [comment]
Very strange, indeed. Could be a lot of different reason.
Are you sure you use the right radare2 version? `r2 -version`
Is this on the same machine?
Have you used both versions in the same iaito project dir?
How do the generated Makefiles differ (e. g. INCPATH)?

**Comment by aiosin** [comment]
yes, same machine same project.
also the r2 version is corect:
`commit: 4715f1e2b9394aac832ff5f37e6a7504c59fd993 build: 2017-04-03__16:36:15
`

can you tell me how I can diff the generated Makefiles, the only one I have now is the Cmake generated one.

**Comment by ballessay** [comment]
Alright.. so you use cmake as, let's call it, 'meta-make' not qmake. ;)
I'm by no means an cmake expert, but AFAIK cmakes supports different types of generators. The output depends on your Kit configuration (see 'CMake Tool' and 'CMake Generator'). I, for example, have 'Ninja' as generator, so no Makefile to diff.
May I ask why you don't just use the qtcreator version that seems to work?

**Comment by aiosin** [comment]
No I was just confused, because one version works and another doesnt. I'll just use CMake because I gives me the least headaches

**Comment by ballessay** [comment]
Maybe the newer version changed the Kit settings? I'm not sure how the qtcreator guys handle version upgrades or the use of different version.

> I'll just use CMake because I gives me the least headaches

Well that's the reason for me to use qmake (at least in projects using Qt)

I guess you could try to let the different versions generate the output in different build directory (Projects -> Build -> Build directory) and compare them with the diff tool of your choice.

**Comment by radare** [comment]
You must buy a new version of r2

**Comment by Maijin** [comment]
Old version of r2.

**Comment by aiosin** [comment]
okay, how do I ensure without chance of failure that I have the correct version of r2 ? 

this is my current installation that I have installed via the submodule and `sys/install.sh`

```
zython5@zython:~$ r2 -version
radare2 1.4.0-git 14345 @ linux-x86-64 git.1.3.0-228-g4715f1e
commit: 4715f1e2b9394aac832ff5f37e6a7504c59fd993 build: 2017-04-03__16:36:15
```

**Comment by hteso** [comment]
I'll update the submodule ASAP and then we can check if it solves the issue.

**Comment by radare** [comment]
Theres no way to update the submodule because it wasnt stuck at any commit at all. I have done that change. Always use r2 from git until r2-1.4 is released

**Comment by aiosin** [comment]
Project just built, after I tried it once more, I have no idea why, should I close the issue ?

Is anyone else experiencing this ?

**Comment by radare** [comment]
Yes pls close
