### ISSUE TITLE
XREF TO doesn't work

### ISSUE THREAD

**Issue by Maijin** [hteso/iaito#7]
See how `VX` is done on visual mode of radare2.

**Comment by trufae** [comment]
But use axtj instead of api :p

**Comment by hteso** [comment]
They work again to me. Can anyone check?

**Comment by Maijin** [comment]
Doesn't work:

![image](https://cloud.githubusercontent.com/assets/1408600/24651316/adf6f306-192d-11e7-9b3b-0e2c964f7646.png)
![image](https://cloud.githubusercontent.com/assets/1408600/24651319/b063d186-192d-11e7-9a85-155287935a22.png)
![image](https://cloud.githubusercontent.com/assets/1408600/24651332/b4751eec-192d-11e7-957c-bcad8f416736.png)

**Comment by hteso** [comment]
Indeed, the seem to work "sometimes".

**Comment by Maijin** [comment]
Ok it's because the right click xrefs is done on the current function not on the selected operand
