### ISSUE TITLE
Enable asm.midflags, otherwise we miss real code in the way iaito uses r2 to disasm

### ISSUE THREAD

**Issue by radare** [hteso/iaito#71]
![screen shot 2017-04-04 at 11 15 07](https://cloud.githubusercontent.com/assets/917142/24649627/0dad50de-1928-11e7-83c6-74ed2691e273.png)

**Comment by radare** [comment]
see https://github.com/hteso/iaito/blob/master/src/qrcore.cpp#L648

**Comment by hteso** [comment]
Added with a value of `2`. Closing
