### ISSUE TITLE
x and X should show all the xrefs from/to available

### ISSUE THREAD

**Issue by Maijin** [hteso/iaito#74]
Just like in visual mode, and allow the user to select

x
![image](https://cloud.githubusercontent.com/assets/1408600/24651438/1f241e78-192e-11e7-8a5f-f3965a5f83b3.png)

X
![image](https://cloud.githubusercontent.com/assets/1408600/24651454/2b4f0ca8-192e-11e7-824f-7a297ba7e5d9.png)

**Comment by hteso** [comment]
There is one single dialog for the xrefs to and from, so the keys x/X would launch the same, and it is Ok for me. Right now the "x" opens the hexdump view so, if we make this change, we need to decide what key use for the hexdump view.

Proposals?

**Comment by Maijin** [comment]
Right click, hexdump

**Comment by radare** [comment]
What about using < for xrefs and > for refs?

**Comment by Maijin** [comment]
No keep it consistent with visual mode and all the other existing tools, much better with x and X

**Comment by trufae** [comment]
current xrefs/refs in side bar are wrong. i think iaito uses the api of r2 as he expects it to work. and axt/axf seems to work fine, so maybe its a bug in r2 api that we can fix in here if we change this to use axtj and axfj and parse the json
