### ISSUE TITLE
Panel to list Exports

### ISSUE THREAD

**Issue by Maijin** [hteso/iaito#78]
iEj, Panel to list Exports

**Comment by hteso** [comment]
Please elaborate the description, I don't get what you are asking for :)

**Comment by Maijin** [comment]
Just like a panel exist for the imports. Another panel should be done for the exports
![image](https://cloud.githubusercontent.com/assets/1408600/24655029/aa93c860-193c-11e7-8eca-c1bac36a1ca4.png)
