### ISSUE TITLE
Remove Syntax ATT/Intel from right click and add all the syntax

### ISSUE THREAD

**Issue by Maijin** [hteso/iaito#83]
This should be only a preference not in right click.
Moreover there is also:
 
```
[0x1000011e0]> e asm.syntax =?
att
intel
masm
jz
regnum
```

**Comment by Maijin** [comment]
Same with Switch Case, this should be a preference not in right click.

**Comment by xarkes** [comment]
Fixed in https://github.com/hteso/iaito/commit/2e79090a1146313aed338f97ea950d95cc32ef4f
