### ISSUE TITLE
Right click need selection before to work

### ISSUE THREAD

**Issue by Maijin** [hteso/iaito#84]
See right click on the other function show me entry0 xrefs From/To

![image](https://cloud.githubusercontent.com/assets/1408600/24657592/200e4656-1947-11e7-98a8-bc1ff7f5c568.png)

**Comment by pwntester** [comment]
Fixed in https://github.com/hteso/iaito/commit/bbb576197cd4b893da98891fec54ab94cecb7ada. Closing

**Comment by Maijin** [comment]
Not fixed here.

**Comment by hteso** [comment]
Reopening

**Comment by Maijin** [comment]
Still not fixed
