### ISSUE TITLE
Enable Travis CI

### ISSUE THREAD

**Issue by probonopd** [hteso/iaito#85]
Thanks for merging https://github.com/hteso/iaito/pull/54, but it is worthless unless you also [enable Travis CI ](https://travis-ci.org/getting_started) so that we can see builds happening at https://travis-ci.org/hteso/iaito. 

Please let me know if the steps are unclear and I should explain it more.
Thanks.

**Comment by hteso** [comment]
Should be enabled :)

**Comment by probonopd** [comment]
Thank you, seems to have worked: at the end of each Travis CI build log, you will find a download URL.
