### ISSUE TITLE
use clang-format

### ISSUE THREAD

**Issue by mrexodia** [hteso/iaito#89]
We should use a tool like [clang-format](https://clang.llvm.org/docs/ClangFormat.html) to enforce code formatting.

**Comment by trufae** [comment]
Theres  no perfect tool for this. All of them fail in some way or other and result in different outputs depending on version.

See r2-indent, and related issues. We use uncrustify which works better than clang format but its far from perfect. I would not enforce that.

Also qtcreator have its own indentation code which works reasonabily and sticks to the qt coding styles which seems more apropiate

**Comment by mrexodia** [comment]
We settles on AStyle, it works great!
