### ISSUE TITLE
UI responsiveness not working anymore

### ISSUE THREAD

**Issue by hteso** [hteso/iaito#97]

**Comment by mrexodia** [comment]
I might have broken this again because the current code doesn't return anything and causes an error on MSVC (as it should since it's undefined behavior).

What should the 'responsive' option do exactly and how can I see if it's broken or not?

**Comment by mrexodia** [comment]
![](https://i.imgur.com/mWy788Q.png)

**Comment by hteso** [comment]
We should add the "Toggle responsiveness" command in the omnibar:

https://github.com/hteso/iaito/blob/master/src/widgets/omnibar.cpp#L23
